name: Continuous Release
on:
  push:
    branches:
      - master
jobs:
  create-zip:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'release')"
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: /*
          dest: BK_Zeugnisse.$(date +'%d-%m-%Y').${{ github.run_number }}.zip.zip
          allowUpdates: true
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.GITHUB_TOKEN }}
